[build-system]
requires = [
    'setuptools>=42',
    'wheel',
    'setuptools_scm[toml]>=3.4',
    'build',
    'twine'
]

# Add an empty tool section to enable version inference.
[tool.setuptools_scm]
write_to = 'pyprof/_version.py'

[tool.flake8]
ignore = ['E501','W503','W504','W291']

[tool.pylint.reports]
output-format = 'colorized'